little improvement of translator ach.po
translate/virtaal pull request #3253
Opened 2016-11-06 09:29 UTC by taufiqsumadi

I found some bugs:
1. Different whitespace at the end
2. missing variable
3. Different XML tags
4. Different functions
5. Different whitespace at the end
6. Different numbers
I hope some improvements can be helpful ;) @julen

2016-11-07 01:51 UTC, jayvdb reviewed
I am just highlighting changes that the maintainers should focus on.

2016-11-07 01:51 UTC, jayvdb commented on po/cs.po
> +msgstr "Přidat \"%s\" do slovníku"
This change needs to be reviewed carefully.  Maybe smart quotes are better.

2016-11-07 01:51 UTC, jayvdb commented on po/cs.po
> +msgstr "Vyhledat \"%(selection)s\""
smart quotes again

2016-11-07 01:51 UTC, jayvdb commented on po/cs.po
> +msgstr "\"%s\" není použitelný soubor."
smart quotes again

2016-11-07 01:51 UTC, jayvdb commented on po/cs.po
> +msgstr "Soubor záznamu '%(filename)s' se nepodařilo otevřít"
smart quotes again

2016-11-07 01:51 UTC, jayvdb commented on po/cs.po
> +msgstr "Konfigurační soubor '%(filename)s' se nepodařilo načíst"
smart quotes again

2016-11-07 01:51 UTC, jayvdb commented on po/cs.po
> +msgstr "Profilovací soubor '%(filename)s' se nepodařilo otevřít"
smart quotes again

2016-11-07 01:51 UTC, jayvdb commented on po/it.po
> +"Per segnare la presente traduzione come fuzzy, basta premere <Alt+U>."
Adding quotes around English words is fairly common in translations.

2016-11-07 01:51 UTC, jayvdb commented on po/it.po
> -"Per segnare la presente traduzione come \"incompleta\", basta premere <Ctrl"
interesting change; perhaps the source string should have quotes around it.

2016-11-07 01:51 UTC, jayvdb commented on po/it.po
> -"Per segnare la presente traduzione come \"completa\", basta premere <Ctrl"
likewise quotes in the source string might be helpful.

2016-11-07 09:16 UTC, dwaynebailey commented on po/cs.po
> +msgstr "Přidat \"%s\" do slovníku"
Quoting styles are language specific.  This looks perfectly correct for `cs`.  Likely you ran pofilter with specifying a language as there are language specific adaptation.

2016-11-07 09:28 UTC, dwaynebailey requested changes
We use technical failures to indicate issues in the translated text.  By cleaning these up and not having a translator clean them up we lost some of these markers.

That said the patch is fine to land with some fixes.

There are only one or two quotes fixes that are correct.  '' -> " is correct.  The others are different quote styles or using quotes in the target.  Those are all fine.

Trailing whitespace and punctuation fixes can land.

Fixing <Xml> is risky in that there could be bigger issues, but they can land.

Fixing variables. The usually all need fixing. The %s one is easy as its almost always an issue. The %filename is harder as we don't know how the language works in terms of prefixing such words.  But all those can land.

Thanks for the  patch, there are some good fixes here.

2016-11-07 09:28 UTC, dwaynebailey commented on po/cs.po
> +msgstr "%.1f KB"
The ACRONYM filter is dumb.  It is simply flagging potential errors.  kB is perfectly correct in some locales, in fact our source could be considered incorrect.

2016-11-07 09:28 UTC, dwaynebailey commented on po/cs.po
> +msgstr "Copyright © 2007-2010 Zuza Software Foundation"
I wouldn't worry about this number as its part of a date range.  Likely the source should say 2007-2016.  So its OK to land, just not critical and not more correct.

2016-11-07 09:28 UTC, dwaynebailey commented on po/it.po
> +"Alla fine della traduzione, premere semplicemente <Enter> per continuare con "
The problem with correcting any of these 'XML' is that they probably need a review of the whole string from a language perspective.  Lets land this one, but be aware that you don't know the software enough to know if someone has just reused another string.

2016-11-07 09:28 UTC, dwaynebailey commented on po/it.po
> +"Per segnare la presente traduzione come fuzzy, basta premere <Alt+U>."
The translator is highlighting that the word fuzzy here is untranslated or borrowed, so leave the quotes.  The quotes checker is a guide not a hard and fast rule.  This we'd consider a false positive.

2016-11-07 09:28 UTC, dwaynebailey commented on po/it.po
> -"Per segnare la presente traduzione come \"incompleta\", basta premere <Ctrl"
As above

2026-09-02 21:00 UTC, dwaynebailey commented
Thanks for this! The ach.po and it.po changes landed as part of #3349, with full attribution - though on review a few of the it.po changes were reverted, since the original translator's choices were actually correct there (<Invio> is the correct Italian word for Enter, and the quotes around "fuzzy"/"incompleta"/"completa" were marking them as UI-status terms deliberately). The cs.po quote changes were also reverted - replacing correct Czech typographic quotes („...", ‚...') with plain ASCII ones was a regression, not an improvement. The genuinely valuable fixes across all three files - missing/garbled format specifiers, a wrong keybinding reference, and a couple of mistranslated format-string identifiers (the same class of bug that turned up separately in ach.po/si.po/zh_TW.po) - did land.

2026-09-02 21:00 UTC, closed without merging